### PR TITLE
Allow toBBox to be extended

### PR DESCRIPTION
**Pull request by DenisCarriere**
@mourner These two minor line changes will make a huge difference to extend both `search()` & `collide()` while using a custom BBox formatter (what I'm currently attempting to do for `@turf/index`).

Here's an example of extending RBush using GeoJSON.

```javascript
var bbox = require('@turf/bbox')

rbush.prototype.toBBox = function (item) {
    var bbox = item.bbox ? item.bbox : bbox(item);
    return {
        minX: bbox[0],
        minY: bbox[1],
        maxX: bbox[2],
        maxY: bbox[3]
    }
}
```
This wont' impact any performance since the default `toBBox()` simply returns the input given.

### CODE REVIEW

**Comment by mourner** [comment]
Unfortunately this breaks custom formats in subtle ways. See #54 for motivation of why I haven't done this.

**Comment by DenisCarriere** [comment]
Humm.. ok... That's unfortunate, ok what I'll do is copy over the RBush `index.js` into the Turf repo and modify it there.

👍 Thanks for the quick response!

**Comment by mourner** [comment]
I would suggest extending rather than copy-pasting. Can you do something like this?

```js
tree.search = function (bbox) {
    return rbush.prototype.search.call(this.toBBox(bbox));
};
```

**Comment by DenisCarriere** [comment]
👍 Cool! Didn't know you could do that, I'll try it out.

**Comment by mourner** [comment]
@DenisCarriere that's how `super` keyword works in ES6 under the hood. The code above had an error, corrected now.

**Comment by DenisCarriere** [comment]
Ops, yea this PR won't work... humm.. this seems to be more complicated than what I first intended to do.

**Pull request closed without merging**
