### PR TITLE
Avoid false positives

### PR DESCRIPTION
**Pull request by Llorx**
Avoid false positives when a box starts where another box ends and do not overlap. https://github.com/mourner/rbush/issues/108

### CODE REVIEW

**Comment by Llorx** [comment]
Yep, there's a test to explicitly select bboxes that do not overlap but are next to each other, which is out of the norm for bboxes. For example, in browsers the bbox are next to each other but do not overlap: https://jsfiddle.net/rkofw4uL/

**Comment by Llorx** [comment]
Just noticed it happens with the other side too.

**Comment by mourner** [comment]
As discussed in the ticket, the query box touching the item bounding box is an intersecting relationship too.

**Comment by Llorx** [comment]
Hm, but this is not default behaviour, for example, in browsers.

Can we, maybe, do something with this? Maybe just create a RBush instance with an option to avoid "touching intersections" which will use one method or another depending on this option. Something like `{ touching: false }`.

**Pull request closed without merging**
