### PR TITLE
Added nearest function to retrieve nearest object to a point

### PR DESCRIPTION
**Pull request by benjamind**
Added this since I needed to be able to retrieve the object closest to a given point.

Not particularly happy with the _distance function, I'm sure that this could be optimized as it seems to have more comparisons than are strictly necessary.

### CODE REVIEW

**Comment by korczis** [comment]
:+1: Can we review and integrate this, please?

**Comment by mourner** [comment]
@korczis can you read the comments above first, please?

**Comment by ischenkodv** [comment]
In this implementation the _distance function computes distance from point to nearest edge of rectangle assuming cartesian coordinates. This is not going to correctly work for geographic coordinates system.

**Comment by mourner** [comment]
I think I'm going to attempt writing an rbush-knn plugin that uses a similar approach to this one but uses priority queue https://github.com/mourner/tinyqueue for maintaining the active list efficiently.

**Comment by korczis** [comment]
@mourner That wikk be awesome

**Comment by mourner** [comment]
Just released https://github.com/mourner/rbush-knn, please check it out! It should be much much faster than this implementation.

**Pull request closed without merging**
